version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${API_DB_USER:-postgres}
      - POSTGRES_PASSWORD=${API_DB_PASSWORD:-postgres}
      - POSTGRES_DB=${API_DB_NAME:-postgres}
    env_file:
      - .env
    ports:
      - "${API_DB_PORT:-5432}:5432"
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data

  frontend:
    build: ../reactjs_fe_plgrnd
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    restart: always
    env_file:
      - .env
