"""Add indexes and unique constraint to Like model

Revision ID: 3fc3a9b39468
Revises: 3dd7971885b6
Create Date: 2025-06-23 13:55:26.025320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fc3a9b39468'
down_revision: Union[str, None] = '3dd7971885b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_likeable_uc', 'likes', ['likeable_type', 'likeable_id'])
    op.create_index(op.f('ix_likes_likeable_id'), 'likes', ['likeable_id'], unique=False)
    op.create_index(op.f('ix_likes_likeable_type'), 'likes', ['likeable_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_likes_likeable_type'), table_name='likes')
    op.drop_index(op.f('ix_likes_likeable_id'), table_name='likes')
    op.drop_constraint('_likeable_uc', 'likes', type_='unique')
    # ### end Alembic commands ###
